#!/usr/bin/env bash
#
# Mặc Hội Tiên Đồ — VPS first-time provisioning
# Chạy 1 lần đầu trên VPS (root). Cài nginx + firewall + setup dirs.
#
# Cách dùng:
#   # Trên máy local:
#   scp scripts/setup-vps.sh scripts/nginx-mac-do.conf root@91.108.104.135:/tmp/
#   ssh root@91.108.104.135 'bash /tmp/setup-vps.sh'
#
# Hoặc all-in-one:
#   ssh root@91.108.104.135 'bash -s' < scripts/setup-vps.sh

set -euo pipefail

VPS_PATH="/var/www/mac-do"
NGINX_SITE="mac-do"
DOMAIN_OR_IP="${DOMAIN_OR_IP:-91.108.104.135}"   # override: DOMAIN_OR_IP=tu-tien.example.com bash setup-vps.sh

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
log() { echo -e "${BLUE}▸${NC} $*"; }
ok()  { echo -e "${GREEN}✓${NC} $*"; }
warn(){ echo -e "${YELLOW}⚠${NC} $*"; }

# ──────────────────────────────────────────────────────────────
# Detect OS
# ──────────────────────────────────────────────────────────────
if ! command -v apt-get >/dev/null 2>&1; then
  echo "Script này chỉ support Debian/Ubuntu (cần apt-get)"
  exit 1
fi
ok "Debian/Ubuntu detected"

# ──────────────────────────────────────────────────────────────
# Install nginx + certbot + utilities
# ──────────────────────────────────────────────────────────────
log "Update apt + install packages..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq nginx certbot python3-certbot-nginx ufw rsync curl
ok "Packages installed"

# ──────────────────────────────────────────────────────────────
# Firewall
# ──────────────────────────────────────────────────────────────
log "Setup firewall (ufw)..."
ufw --force enable >/dev/null 2>&1 || true
ufw allow 22/tcp >/dev/null   # SSH
ufw allow 80/tcp >/dev/null   # HTTP
ufw allow 443/tcp >/dev/null  # HTTPS
ok "Firewall: SSH/HTTP/HTTPS allowed"

# ──────────────────────────────────────────────────────────────
# Create dirs
# ──────────────────────────────────────────────────────────────
log "Tạo directory structure..."
mkdir -p "$VPS_PATH"/{releases,backups,current}
chown -R www-data:www-data "$VPS_PATH"
chmod -R 755 "$VPS_PATH"
ok "$VPS_PATH/ ready"

# ──────────────────────────────────────────────────────────────
# Initial placeholder page
# ──────────────────────────────────────────────────────────────
if [[ ! -f "$VPS_PATH/current/index.html" ]]; then
  cat > "$VPS_PATH/current/index.html" <<HTML
<!DOCTYPE html>
<html lang="vi"><head><meta charset="UTF-8"><title>Mặc Hội Tiên Đồ</title>
<style>body{background:#0a0f0a;color:#e8d3a1;font-family:Georgia,serif;display:flex;align-items:center;justify-content:center;height:100vh;margin:0;text-align:center}</style>
</head><body><div>
<h1 style="color:#cda45e">Mặc Hội Tiên Đồ</h1>
<p>VPS đã setup xong, chờ deploy đầu tiên...</p>
<p style="font-family:monospace;font-size:12px;color:#8ba888">./scripts/deploy.sh</p>
</div></body></html>
HTML
  ok "Placeholder page tạo xong"
fi

# ──────────────────────────────────────────────────────────────
# Nginx config
# ──────────────────────────────────────────────────────────────
log "Setup nginx site config..."

# Nếu /tmp/nginx-mac-do.conf đã được scp lên thì copy, không thì tạo inline
if [[ -f /tmp/nginx-mac-do.conf ]]; then
  cp /tmp/nginx-mac-do.conf "/etc/nginx/sites-available/$NGINX_SITE"
else
  cat > "/etc/nginx/sites-available/$NGINX_SITE" <<NGINX
# Mặc Hội Tiên Đồ — nginx site config (auto-generated by setup-vps.sh)
server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN_OR_IP;

    root $VPS_PATH/current;
    index index.html;

    access_log /var/log/nginx/mac-do.access.log;
    error_log /var/log/nginx/mac-do.error.log;

    # Gzip
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types text/plain text/css text/javascript application/javascript application/json image/svg+xml application/wasm;

    # SPA fallback
    location / {
        try_files \$uri \$uri/ /index.html;
    }

    # Cache assets with hash (immutable)
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    # Cache lottie + manifest
    location ~* \.(svg|json|webmanifest|woff2?)\$ {
        expires 7d;
        add_header Cache-Control "public";
    }

    # Don't cache HTML
    location ~* \.html\$ {
        add_header Cache-Control "no-cache, must-revalidate";
    }

    # Service worker — không cache
    location = /sw.js {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
}
NGINX
fi

ln -sf "/etc/nginx/sites-available/$NGINX_SITE" "/etc/nginx/sites-enabled/$NGINX_SITE"
# Disable default site
rm -f /etc/nginx/sites-enabled/default

if nginx -t 2>&1 | grep -q "successful"; then
  systemctl reload nginx
  ok "Nginx config valid + reloaded"
else
  echo "Nginx config INVALID:"
  nginx -t
  exit 1
fi

# ──────────────────────────────────────────────────────────────
# Test
# ──────────────────────────────────────────────────────────────
log "Smoke test..."
if curl -sf -o /dev/null "http://localhost/"; then
  ok "HTTP serving OK"
else
  echo "Warning: HTTP test fail"
fi

# ──────────────────────────────────────────────────────────────
# Summary
# ──────────────────────────────────────────────────────────────
echo ""
ok "═══════════════════════════════════════════════════"
ok "VPS setup hoàn tất!"
ok "═══════════════════════════════════════════════════"
echo ""
echo "Truy cập: http://$DOMAIN_OR_IP/"
echo ""
echo "Bước tiếp theo (từ máy local):"
echo "  ./scripts/deploy.sh"
echo ""
echo "(Tùy chọn) Setup HTTPS với certbot:"
echo "  certbot --nginx -d $DOMAIN_OR_IP    # cần domain thật, không phải IP"
echo ""
echo "Logs:"
echo "  tail -f /var/log/nginx/mac-do.access.log"
echo "  tail -f /var/log/nginx/mac-do.error.log"
